database:
  host: "139.198.155.59"
  port: 3316
  username: "root"
  password: "root"
  dbname: "vueproject"
  autoMigrate: false

server:
  port: 12080

log:
  filename: "./logs/project.log"
  encoder: "json"
  compress: true
  localtime: true
redis:
  host: "139.198.155.59"
  port: "6389"
  db: 0
